"""Local web dashboards for the lecture notes app - a separate process from the recorder.

Two pages, deliberately separate concerns:
  /             Notes    - read, browse and search everything the recorder has produced
  /diagnostics  Live     - what a running session is doing right now, plus the same
                           controls the terminal has (save now / stop)

Runs as its own process so it can never slow down or crash a recording in progress: it
reads notes/ and state/, offers revision-checked correction writes, and talks to a live
recorder through the two small files in telemetry.py. Starting it while nothing is recording is fine - the notes side works
entirely on its own, and diagnostics just shows the last session's final state.

    python src/dashboard.py [--port 8770] [--no-browser]

Everything is served from this machine with no CDN or external assets, so it works with
no internet - same constraint the rest of the app is built around.
"""
import argparse
import html
import json
import re
import sys
import threading
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent))

import search as search_module
import telemetry
import recorder_launcher

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOTES_DIR = PROJECT_ROOT / "notes"
STATE_DIR = PROJECT_ROOT / "state"
STATIC_DIR = PROJECT_ROOT / "dashboard"

DEFAULT_PORT = 8770


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")


def _inline(text: str) -> str:
    """Escapes first, then re-introduces only the inline formatting we control - notes
    are LLM-generated text, so nothing in them may be trusted as markup."""
    out = html.escape(text)
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    out = _ITALIC.sub(r"<em>\1</em>", out)
    return out


def lecture_anchors(dates):
    seen = {}
    result = []
    for date in dates:
        base = re.sub(r"[^a-z0-9]+", "-", date.lower()).strip("-") or "lecture"
        seen[base] = seen.get(base, 0) + 1
        result.append(base if seen[base] == 1 else f"{base}-{seen[base]}")
    return result


def markdown_to_html(markdown: str) -> str:
    """Handles the limited subset the notes actually use (headings, nested bullets,
    bold/italic). A full markdown library would be a dependency for no benefit - the
    notes are generated by prompts in this repo, so the format is known and bounded."""
    lines_out = []
    list_depth = 0
    anchors = iter(lecture_anchors(re.findall(r"^## (.+)$", markdown, re.MULTILINE)))

    def close_lists(to_depth=0):
        nonlocal list_depth
        while list_depth > to_depth:
            lines_out.append("</ul>")
            list_depth -= 1

    for raw in markdown.split("\n"):
        line = raw.rstrip()
        if not line.strip():
            close_lists()
            continue

        bullet = re.match(r"^(\s*)[-*]\s+(.*)$", line)
        if bullet:
            indent = len(bullet.group(1))
            depth = 1 + (indent // 2)
            while list_depth < depth:
                lines_out.append("<ul>")
                list_depth += 1
            close_lists(depth)
            lines_out.append(f"<li>{_inline(bullet.group(2))}</li>")
            continue

        close_lists()
        if line.startswith("### "):
            lines_out.append(f'<h3>{_inline(line[4:].strip())}</h3>')
        elif line.startswith("## "):
            date = line[3:].strip()
            anchor = next(anchors)
            lines_out.append(f'<h2 id="{anchor}">{_inline(date)}</h2>')
        elif line.startswith("# "):
            lines_out.append(f"<h1>{_inline(line[2:].strip())}</h1>")
        else:
            lines_out.append(f"<p>{_inline(line)}</p>")

    close_lists()
    return "\n".join(lines_out)


# ---------------------------------------------------------------------------
# Data gathering
# ---------------------------------------------------------------------------

def _class_files(code: str) -> dict:
    if code not in {p.stem.replace("_", " ") for p in NOTES_DIR.glob("*.md")
                    if not p.stem.endswith("_study_guide")}:
        return {}
    safe = code.replace(" ", "_")
    return {
        "notes": NOTES_DIR / f"{safe}.md",
        "docx": NOTES_DIR / f"{safe}.docx",
        "study_guide": NOTES_DIR / f"{safe}_study_guide.md",
        "flashcards": NOTES_DIR / f"{safe}_flashcards_anki.txt",
    }


def list_classes() -> list[dict]:
    """Every class that has notes on disk, with enough metadata for the sidebar."""
    if not NOTES_DIR.exists():
        return []
    out = []
    for path in sorted(NOTES_DIR.glob("*.md")):
        if path.stem.endswith("_study_guide"):
            continue
        code = path.stem.replace("_", " ")
        text = path.read_text(encoding="utf-8", errors="replace")
        title_match = re.match(r"^# (.+?)\s*\(", text)
        dates = re.findall(r"^## (.+)$", text, re.MULTILINE)
        files = _class_files(code)
        out.append({
            "code": code,
            "title": title_match.group(1).strip() if title_match else code,
            "lectures": len(dates),
            "latest": dates[-1] if dates else "",
            "words": len(text.split()),
            "updated": path.stat().st_mtime,
            "has_study_guide": files["study_guide"].exists(),
            "has_flashcards": files["flashcards"].exists(),
            "has_docx": files["docx"].exists(),
        })
    return out


def class_document(code: str, kind: str = "notes") -> dict:
    files = _class_files(code)
    path = files.get(kind)
    if not path or not path.exists():
        return {"error": f"no {kind} for {code}"}
    text = path.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"<!-- /?session:[A-Za-z0-9_-]+ -->", "", text)
    if kind == "flashcards":
        cards = []
        for line in text.splitlines():
            if line.startswith("#") or "\t" not in line:
                continue
            front, back = line.split("\t", 1)
            cards.append({"front": front, "back": back})
        return {"code": code, "kind": kind, "cards": cards}
    dates = re.findall(r"^## (.+)$", text, re.MULTILINE)
    return {
        "code": code,
        "kind": kind,
        "html": markdown_to_html(text),
        "toc": [{"date": date, "anchor": anchor}
                for date, anchor in zip(dates, lecture_anchors(dates))],
        "words": len(text.split()),
        "updated": path.stat().st_mtime,
    }


def list_sessions() -> list[dict]:
    """Recorded sessions from state/, newest first - the raw audio + transcript backups
    behind each lecture."""
    if not STATE_DIR.exists():
        return []
    out = []
    for wav in sorted(STATE_DIR.glob("*.wav"), reverse=True):
        stem = wav.stem
        match = re.match(r"^(.+)_(\d{8})_(\d{6})$", stem)
        if not match:
            continue
        raw = wav.with_name(f"{stem}_raw.txt")
        size = wav.stat().st_size
        out.append({
            "class_code": match.group(1).replace("_", " "),
            "date": f"{match.group(2)[:4]}-{match.group(2)[4:6]}-{match.group(2)[6:]}",
            "time": f"{match.group(3)[:2]}:{match.group(3)[2:4]}",
            "minutes": round(size / (2 * 16000 * 2) / 60, 1),  # float32 mono @16k
            "mb": round(size / 1e6, 1),
            "wav": wav.name,
            "has_transcript": raw.exists(),
            "transcript_lines": len(raw.read_text(encoding="utf-8", errors="replace").splitlines())
                                 if raw.exists() else 0,
        })
    return out


def service_status() -> dict:
    """Point-in-time health of everything the recorder depends on. Imported lazily
    because notes/gpu_formatter pull in the rest of the app, and the dashboard should
    still start (and serve notes) even if one of them is broken."""
    status = {}
    try:
        import notes as notes_module
        status["claude_cli"] = "available" if notes_module.cli_available() else "unavailable"
    except Exception as e:
        status["claude_cli"] = f"error: {type(e).__name__}"
    try:
        import os
        status["claude_api"] = "key set" if os.environ.get("ANTHROPIC_API_KEY") else "no key"
    except Exception:
        status["claude_api"] = "unknown"
    try:
        import gpu_formatter
        if not gpu_formatter.available():
            status["gpu_model"] = "not installed"
        else:
            status["gpu_model"] = "running" if gpu_formatter._server_healthy() else "installed (stopped)"
    except Exception as e:
        status["gpu_model"] = f"error: {type(e).__name__}"
    try:
        import diarize
        status["diarization"] = "enabled" if diarize.available() else "off (no HF token)"
    except Exception as e:
        status["diarization"] = f"error: {type(e).__name__}"
    return status


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass  # the default logger spams a line per poll; the dashboard polls constantly

    def _send(self, body: bytes, content_type: str, status: int = 200):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, payload, status: int = 200):
        self._send(json.dumps(payload).encode("utf-8"), "application/json", status)

    def _static(self, name: str, content_type: str):
        path = STATIC_DIR / name
        if not path.exists():
            self._send(b"not found", "text/plain", 404)
            return
        self._send(path.read_bytes(), content_type)

    def _audio(self, filename):
        # Only named recordings directly inside state/ may be streamed.
        if not re.fullmatch(r"[A-Za-z0-9_-]+_\d{8}_\d{6}\.wav", filename):
            self._send(b"invalid recording", "text/plain", 400)
            return
        path = (STATE_DIR / filename).resolve()
        if path.parent != STATE_DIR.resolve() or not path.is_file():
            self._send(b"recording not found", "text/plain", 404)
            return
        with path.open("rb") as handle:
            size = path.stat().st_size
            start, end, status = 0, size - 1, 200
            requested = self.headers.get("Range")
            if requested:
                match = re.fullmatch(r"bytes=(\d*)-(\d*)", requested)
                try:
                    if not match or not any(match.groups()):
                        raise ValueError()
                    first, last = match.groups()
                    if first:
                        start = int(first)
                        end = min(int(last), size - 1) if last else size - 1
                    else:
                        start = max(0, size - int(last))
                    if start > end or start >= size:
                        raise ValueError()
                except ValueError:
                    self.send_response(416)
                    self.send_header("Content-Range", f"bytes */{size}")
                    self.send_header("Content-Length", "0")
                    self.end_headers()
                    return
                status = 206
            self.send_response(status)
            self.send_header("Content-Type", "audio/wav")
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Content-Length", str(end - start + 1))
            if status == 206:
                self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
            self.end_headers()
            handle.seek(start)
            remaining = end - start + 1
            try:
                while remaining:
                    block = handle.read(min(65536, remaining))
                    if not block:
                        break
                    self.wfile.write(block)
                    remaining -= len(block)
            except (BrokenPipeError, ConnectionResetError):
                pass  # browser seeking/cancelling is normal

    def do_GET(self):
        parsed = urlparse(self.path)
        route = parsed.path
        params = parse_qs(parsed.query)

        def one(key, default=None):
            return params.get(key, [default])[0]

        if route == "/api/audio":
            self._audio(one("file", ""))
        elif route == "/":
            self._static("notes.html", "text/html; charset=utf-8")
        elif route == "/diagnostics":
            self._static("diagnostics.html", "text/html; charset=utf-8")
        elif route == "/corrections":
            self._static("corrections.html", "text/html; charset=utf-8")
        elif route.startswith("/api/corrections/"):
            try:
                import corrections
                if route == "/api/corrections/sessions":
                    self._json(corrections.list_sessions())
                elif route == "/api/corrections/session":
                    self._json(corrections.workspace(one("session","")))
                elif route == "/api/corrections/job":
                    self._json(corrections.get_job(one("id","")))
                else:
                    self._json({"error":"Unknown correction route"},404)
            except FileNotFoundError as error:
                self._json({"error":str(error)},404)
            except ValueError as error:
                self._json({"error":str(error)},409)
        elif route == "/style.css":
            self._static("style.css", "text/css; charset=utf-8")
        elif route == "/api/classes":
            self._json(list_classes())
        elif route == "/api/document":
            self._json(class_document(one("class", ""), one("kind", "notes")))
        elif route == "/api/search":
            query = one("q", "") or ""
            if not query.strip():
                self._json([])
                return
            hits = search_module.search(
                query,
                class_code=one("class") or None,
                include_transcripts=one("transcripts", "1") == "1",
            )
            self._json([{
                "class_code": h.class_code, "source": h.source, "location": h.location,
                "text": h.text, "line": h.line_number, "timestamp": h.timestamp,
                "section": h.section, "audio_file": h.audio_file,
                "audio_seconds": h.audio_seconds,
            } for h in hits[:400]])
        elif route == "/api/sessions":
            self._json(list_sessions())
        elif route == "/api/status":
            payload = telemetry.read_status()
            payload["services"] = service_status()
            payload["recorder"] = recorder_launcher.recorder_state()
            self._json(payload)
        else:
            self._send(b"not found", "text/plain", 404)

    def _local_host(self) -> bool:
        """The request was addressed to this dashboard's own loopback address and port."""
        try:
            host = urlparse("http://" + self.headers.get("Host", ""))
            return (host.hostname in ("127.0.0.1", "localhost", "::1")
                    and host.port == self.server.server_port)
        except ValueError:
            return False

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path.startswith("/api/corrections/"):
            self._correction_post(parsed.path)
            return
        if parsed.path != "/api/command":
            self._send(b"not found", "text/plain", 404)
            return
        origin=self.headers.get('Origin')
        # Host check first: under DNS rebinding a hostile page is same-origin with itself,
        # so Origin == Host alone would still let it stop or start a recording.
        if (not self._local_host() or (origin and origin != 'http://'+self.headers.get('Host',''))
                or self.headers.get('X-Notes-Dashboard')!='1'):
            self._json({'ok':False,'error':'Commands must come from this dashboard.'},403)
            return
        try:
            length = int(self.headers.get("Content-Length", 0))
            if not 0<=length<=4096:raise ValueError('Invalid request size')
            body = json.loads(self.rfile.read(length) or b"{}")
            if not isinstance(body,dict):raise ValueError('Expected an object')
        except Exception:
            self._json({'ok':False,'error':'Invalid command request.'},400)
            return
        action = body.get("action", "")
        if action == 'start':
            try:self._json(recorder_launcher.start_recorder())
            except (OSError,RuntimeError) as exc:self._json({'ok':False,'error':str(exc)},500)
            return
        if action not in ("save_now", "stop"):
            self._json({"ok": False, "error": "unknown action"}, 400)
            return
        self._json({"ok": telemetry.send_command(action)})

    def _correction_post(self, route):
        from storage import RevisionConflict
        try:
            # Browser writes must come from this dashboard and use JSON.
            origin = self.headers.get("Origin")
            if not self._local_host():
                self._json({"error":"Correction writes require the local dashboard address"},403)
                return
            if origin is not None and origin != "http://" + self.headers.get("Host", ""):
                self._json({"error":"Open the correction workspace on this dashboard to save edits"},403)
                return
            if self.headers.get_content_type() != "application/json":
                self._json({"error":"JSON request required"},415)
                return
            length = int(self.headers.get("Content-Length","0"))
            if not 0 < length <= 1_000_000:
                self._json({"error":"Request is empty or too large"},413)
                return
            payload = json.loads(self.rfile.read(length))
            if not isinstance(payload,dict):
                raise ValueError("Expected a JSON object")
            import corrections
            actions = {"/api/corrections/save":corrections.save_correction,
                       "/api/corrections/regenerate":corrections.start_regeneration,
                       "/api/corrections/apply":corrections.apply_preview}
            if route not in actions:
                self._json({"error":"Unknown correction route"},404)
                return
            self._json(actions[route](payload))
        except RevisionConflict as error:
            self._json({"error":str(error)},409)
        except (ValueError,TypeError) as error:
            self._json({"error":str(error)},400)
        except FileNotFoundError as error:
            self._json({"error":str(error)},404)
        except Exception as error:
            self._json({"error":str(error)},500)


def serve(port: int = DEFAULT_PORT, open_browser: bool = True):
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    url = f"http://127.0.0.1:{port}"
    print(f"Lecture notes dashboard: {url}")
    print(f"Diagnostics:             {url}/diagnostics")
    print("Ctrl+C to stop.")
    if open_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nDashboard stopped.")
        server.shutdown()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Lecture notes dashboards")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--no-browser", action="store_true", help="Don't auto-open a browser")
    args = parser.parse_args()
    serve(args.port, not args.no_browser)
