"""Local web dashboards for the lecture notes app - a separate process from the recorder.

Two pages, deliberately separate concerns:
  /             Notes    - read, browse and search everything the recorder has produced
  /diagnostics  Live     - what a running session is doing right now, plus the same
                           controls the terminal has (save now / stop)

Runs as its own process so it can never slow down or crash a recording in progress: it
only reads notes/ and state/, and talks to a live recorder through the two small files
in telemetry.py. Starting it while nothing is recording is fine - the notes side works
entirely on its own, and diagnostics just shows the last session's final state.

    python src/dashboard.py [--port 8770] [--no-browser]

Everything is served from this machine with no CDN or external assets, so it works with
no internet - same constraint the rest of the app is built around.
"""
import argparse
import html
import json
import re
import sys
import threading
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent))

import search as search_module
import telemetry

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOTES_DIR = PROJECT_ROOT / "notes"
STATE_DIR = PROJECT_ROOT / "state"
STATIC_DIR = PROJECT_ROOT / "dashboard"

DEFAULT_PORT = 8770


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)")


def _inline(text: str) -> str:
    """Escapes first, then re-introduces only the inline formatting we control - notes
    are LLM-generated text, so nothing in them may be trusted as markup."""
    out = html.escape(text)
    out = _BOLD.sub(r"<strong>\1</strong>", out)
    out = _ITALIC.sub(r"<em>\1</em>", out)
    return out


def markdown_to_html(markdown: str) -> str:
    """Handles the limited subset the notes actually use (headings, nested bullets,
    bold/italic). A full markdown library would be a dependency for no benefit - the
    notes are generated by prompts in this repo, so the format is known and bounded."""
    lines_out = []
    list_depth = 0

    def close_lists(to_depth=0):
        nonlocal list_depth
        while list_depth > to_depth:
            lines_out.append("</ul>")
            list_depth -= 1

    for raw in markdown.split("\n"):
        line = raw.rstrip()
        if not line.strip():
            close_lists()
            continue

        bullet = re.match(r"^(\s*)[-*]\s+(.*)$", line)
        if bullet:
            indent = len(bullet.group(1))
            depth = 1 + (indent // 2)
            while list_depth < depth:
                lines_out.append("<ul>")
                list_depth += 1
            close_lists(depth)
            lines_out.append(f"<li>{_inline(bullet.group(2))}</li>")
            continue

        close_lists()
        if line.startswith("### "):
            lines_out.append(f'<h3>{_inline(line[4:].strip())}</h3>')
        elif line.startswith("## "):
            date = line[3:].strip()
            anchor = re.sub(r"[^a-z0-9]+", "-", date.lower()).strip("-")
            lines_out.append(f'<h2 id="{anchor}">{_inline(date)}</h2>')
        elif line.startswith("# "):
            lines_out.append(f"<h1>{_inline(line[2:].strip())}</h1>")
        else:
            lines_out.append(f"<p>{_inline(line)}</p>")

    close_lists()
    return "\n".join(lines_out)


# ---------------------------------------------------------------------------
# Data gathering
# ---------------------------------------------------------------------------

def _class_files(code: str) -> dict:
    safe = code.replace(" ", "_")
    return {
        "notes": NOTES_DIR / f"{safe}.md",
        "docx": NOTES_DIR / f"{safe}.docx",
        "study_guide": NOTES_DIR / f"{safe}_study_guide.md",
        "flashcards": NOTES_DIR / f"{safe}_flashcards_anki.txt",
    }


def list_classes() -> list[dict]:
    """Every class that has notes on disk, with enough metadata for the sidebar."""
    if not NOTES_DIR.exists():
        return []
    out = []
    for path in sorted(NOTES_DIR.glob("*.md")):
        if path.stem.endswith("_study_guide"):
            continue
        code = path.stem.replace("_", " ")
        text = path.read_text(encoding="utf-8", errors="replace")
        title_match = re.match(r"^# (.+?)\s*\(", text)
        dates = re.findall(r"^## (.+)$", text, re.MULTILINE)
        files = _class_files(code)
        out.append({
            "code": code,
            "title": title_match.group(1).strip() if title_match else code,
            "lectures": len(dates),
            "latest": dates[-1] if dates else "",
            "words": len(text.split()),
            "updated": path.stat().st_mtime,
            "has_study_guide": files["study_guide"].exists(),
            "has_flashcards": files["flashcards"].exists(),
            "has_docx": files["docx"].exists(),
        })
    return out


def class_document(code: str, kind: str = "notes") -> dict:
    files = _class_files(code)
    path = files.get(kind)
    if not path or not path.exists():
        return {"error": f"no {kind} for {code}"}
    text = path.read_text(encoding="utf-8", errors="replace")
    if kind == "flashcards":
        cards = []
        for line in text.splitlines():
            if line.startswith("#") or "\t" not in line:
                continue
            front, back = line.split("\t", 1)
            cards.append({"front": front, "back": back})
        return {"code": code, "kind": kind, "cards": cards}
    dates = re.findall(r"^## (.+)$", text, re.MULTILINE)
    return {
        "code": code,
        "kind": kind,
        "html": markdown_to_html(text),
        "toc": [{"date": d, "anchor": re.sub(r"[^a-z0-9]+", "-", d.lower()).strip("-")}
                 for d in dates],
        "words": len(text.split()),
        "updated": path.stat().st_mtime,
    }


def list_sessions() -> list[dict]:
    """Recorded sessions from state/, newest first - the raw audio + transcript backups
    behind each lecture."""
    if not STATE_DIR.exists():
        return []
    out = []
    for wav in sorted(STATE_DIR.glob("*.wav"), reverse=True):
        stem = wav.stem
        match = re.match(r"^(.+)_(\d{8})_(\d{6})$", stem)
        if not match:
            continue
        raw = wav.with_name(f"{stem}_raw.txt")
        size = wav.stat().st_size
        out.append({
            "class_code": match.group(1).replace("_", " "),
            "date": f"{match.group(2)[:4]}-{match.group(2)[4:6]}-{match.group(2)[6:]}",
            "time": f"{match.group(3)[:2]}:{match.group(3)[2:4]}",
            "minutes": round(size / (2 * 16000 * 2) / 60, 1),  # float32 mono @16k
            "mb": round(size / 1e6, 1),
            "wav": wav.name,
            "has_transcript": raw.exists(),
            "transcript_lines": len(raw.read_text(encoding="utf-8", errors="replace").splitlines())
                                 if raw.exists() else 0,
        })
    return out


def service_status() -> dict:
    """Point-in-time health of everything the recorder depends on. Imported lazily
    because notes/gpu_formatter pull in the rest of the app, and the dashboard should
    still start (and serve notes) even if one of them is broken."""
    status = {}
    try:
        import notes as notes_module
        status["claude_cli"] = "available" if notes_module.cli_available() else "unavailable"
    except Exception as e:
        status["claude_cli"] = f"error: {type(e).__name__}"
    try:
        import os
        status["claude_api"] = "key set" if os.environ.get("ANTHROPIC_API_KEY") else "no key"
    except Exception:
        status["claude_api"] = "unknown"
    try:
        import gpu_formatter
        if not gpu_formatter.available():
            status["gpu_model"] = "not installed"
        else:
            status["gpu_model"] = "running" if gpu_formatter._server_healthy() else "installed (stopped)"
    except Exception as e:
        status["gpu_model"] = f"error: {type(e).__name__}"
    try:
        import diarize
        status["diarization"] = "enabled" if diarize.available() else "off (no HF token)"
    except Exception as e:
        status["diarization"] = f"error: {type(e).__name__}"
    return status


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass  # the default logger spams a line per poll; the dashboard polls constantly

    def _send(self, body: bytes, content_type: str, status: int = 200):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, payload, status: int = 200):
        self._send(json.dumps(payload).encode("utf-8"), "application/json", status)

    def _static(self, name: str, content_type: str):
        path = STATIC_DIR / name
        if not path.exists():
            self._send(b"not found", "text/plain", 404)
            return
        self._send(path.read_bytes(), content_type)

    def do_GET(self):
        parsed = urlparse(self.path)
        route = parsed.path
        params = parse_qs(parsed.query)

        def one(key, default=None):
            return params.get(key, [default])[0]

        if route == "/":
            self._static("notes.html", "text/html; charset=utf-8")
        elif route == "/diagnostics":
            self._static("diagnostics.html", "text/html; charset=utf-8")
        elif route == "/style.css":
            self._static("style.css", "text/css; charset=utf-8")
        elif route == "/api/classes":
            self._json(list_classes())
        elif route == "/api/document":
            self._json(class_document(one("class", ""), one("kind", "notes")))
        elif route == "/api/search":
            query = one("q", "") or ""
            if not query.strip():
                self._json([])
                return
            hits = search_module.search(
                query,
                class_code=one("class") or None,
                include_transcripts=one("transcripts", "1") == "1",
            )
            self._json([{
                "class_code": h.class_code, "source": h.source, "location": h.location,
                "text": h.text, "line": h.line_number, "timestamp": h.timestamp,
                "section": h.section,
            } for h in hits[:400]])
        elif route == "/api/sessions":
            self._json(list_sessions())
        elif route == "/api/status":
            payload = telemetry.read_status()
            payload["services"] = service_status()
            self._json(payload)
        else:
            self._send(b"not found", "text/plain", 404)

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path != "/api/command":
            self._send(b"not found", "text/plain", 404)
            return
        length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except Exception:
            body = {}
        action = body.get("action", "")
        if action not in ("save_now", "stop"):
            self._json({"ok": False, "error": "unknown action"}, 400)
            return
        self._json({"ok": telemetry.send_command(action)})


def serve(port: int = DEFAULT_PORT, open_browser: bool = True):
    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    url = f"http://127.0.0.1:{port}"
    print(f"Lecture notes dashboard: {url}")
    print(f"Diagnostics:             {url}/diagnostics")
    print("Ctrl+C to stop.")
    if open_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nDashboard stopped.")
        server.shutdown()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Lecture notes dashboards")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--no-browser", action="store_true", help="Don't auto-open a browser")
    args = parser.parse_args()
    serve(args.port, not args.no_browser)
